.\"
.\" Copyright (c) 2018 Rodrigo Osorio <rodrigo@FreeBSD.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd February 9, 2020
.Dt PKG-PROVIDES 8
.Os
.Sh NAME
.Nm "pkg provides"
.Nd query which package provides a file matching a particular pattern
.Sh SYNOPSIS
.Nm
.Op Fl u
.Op Fl f
.Nm
.Op Fl r Ar repo
.Ar pattern
.Sh DESCRIPTION
.Nm
is used to query which package in your pkg catalog provides a particular
file given a pattern.
.Pp
The search pattern can be any perl compatible regular expression (PCRE).
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width repository
.It Fl u
Check if a new database file is available and then perform the update.
.It Fl f
Force the update.
.It Fl r Ar repo
Restrict search results to a specific repository.
.It Sy pattern
Can be any perl compatible regular expression (PCRE). The search is not case sensitive.
.El
.Sh ENVIRONMENT
.Bl -tag -width "PROVIDES_FETCH_ON_UPDATE"
.It PROVIDES_FETCH_ON_UPDATE
If set to "NO", it disables the default behaviour and doesn't perform a
.Nm
database update after updating pkg.
.It PROVIDES_URL
When set, overrides the default
.Nm
server URL.
The default value is "https://pkg-provides.osorio.me".
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Update the provides database:
.Pp
.Dl $ pkg provides -u
.Pp
Search for a package that provides bin/firefox
.Pp
.Dl $ pkg provides bin/firefox$
.Pp
Search for packages that provide a file with the pattern libbz2.so.*
.Pp
.Dl $ pkg provides ^libbz2.so.
.Pp
Look for bin/firefox but only in the
.Fx
repository
.Pp
.Dl $ pkg provides -r FreeBSD bin/firefox$
.Sh AUTHORS
.An -nosplit
.Nm
.An was written by Rodrigo Osorio <rodrigo@FreeBSD.org> .
